// Create User
POST http://localhost:5000/users
Content-Type: application/json

{
  "name": "Admin",
  "email": "adminfebri@urbanathletes.co.id",
  "password": "Urban1234",
  "confPassword": "Urban1234",
  "role": 1
}

###
// get All user
GET http://localhost:5000/users

###
// get Single user
GET http://localhost:5000/users/da63a8a9-d3c7-4d80-be6b-63dbb43a18da

###
// Update User
PATCH http://localhost:5000/users/da63a8a9-d3c7-4d80-be6b-63dbb43a18da
Content-Type: application/json

{
  "name": "febri Update",
  "email": "febri@urbanathletes.co.id",
  "password": "",
  "confPassword": "",
  "role": 2
}

###
// Delete User
# DELETE http://localhost:5000/users/89c77ed4-98c8-481f-9f75-3ebab95c3589
DELETE http://localhost:5000/users
Content-Type: application/json

{
  "id": "fa1e7ded-7979-44bb-80fc-db3a88626c6c"
}

###
// Login User
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "admin@urbanathletes.co.id",
  "password": "Urban1234"
}

###
// get Auth
GET http://localhost:5000/auth/me
Content-Type: application/json

###
// Logout User
DELETE http://localhost:5000/auth/logout
Content-Type: application/json
